export const fontOptions = [
    { name: 'Montserrat', className: 'font-montserrat' },
    { name: 'Raleway', className: 'font-raleway' },
    { name: 'Poppins', className: 'font-poppins' },
    { name: 'Anton', className: 'font-anton' },
    { name: 'Luckiest Guy', className: 'font-luckiest-guy' },
    { name: 'Bangers', className: 'font-bangers' },
    { name: 'Lilita One', className: 'font-lilita-one' },
    { name: 'Alegreya Sans', className: 'font-alegreya-sans' },
    { name: 'Times New Roman', className: 'font-times' },
    { name: 'Aloja (Dancing Script)', className: 'font-dancing-script' },
    { name: 'Marykate (Kalam)', className: 'font-kalam' },
    { name: 'Selima (Great Vibes)', className: 'font-great-vibes' },
    { name: 'Brown Sugar (Satisfy)', className: 'font-satisfy' },
    { name: 'Brasika (Orbitron)', className: 'font-orbitron' },
    { name: 'Chewy', className: 'font-chewy' },
    { name: 'League Spartan', className: 'font-league-spartan' },
    { name: 'Giaza (Stencil)', className: 'font-stencil' },
    { name: 'Pierson (Playfair)', className: 'font-playfair' },
    { name: 'Quick (Quicksand)', className: 'font-quicksand' },
]